spring.application.name=crud-productos

spring.datasource.url=jdbc:h2:mem:crudproductosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Habilita la consola web de H2 (es un navegador web dentro de tu app)
spring.h2.console.enabled=true
# La URL donde estará disponible la consola: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
# --------------------------------------
# Muestra las consultas SQL que Hibernate ejecuta en la consola del IDE.
spring.jpa.show-sql=true
# Formatea el SQL para que sea legible.
spring.jpa.properties.hibernate.format_sql=true
# Crea las tablas automáticamente basándose en las entidades (@Entity).
# Opciones: create-drop (borra al apagar), update (actualiza esquema), validate, none.
# En desarrollo usamos 'update'. En producción NUNCA usar update.
spring.jpa.hibernate.ddl-auto=update
